services:
  mongo-db:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file: './.env'

  backend:
    build: ./
    container_name: fastapi
    ports:
     - 8000:8000
    depends_on:
      - mongo-db
    env_file: .env


volumes:
  mongo_data:




